# 3-3 Pandas 快速入門

[![在 Colab 開啟](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/finlab-python/hahow-crypto-course/blob/main/3-3_pandas_basics.ipynb)

**對應影片**：第 3 章 單元 3-3【Python 基礎教學】Pandas 快速入門

**和影片的差異**

- 程式碼與影片相同，補上中文說明。

In [1]:
%pip install -q finlab_crypto==0.3.0

Note: you may need to restart the kernel to use updated packages.

## 建立 DataFrame

[DataFrame 文件](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)

- **data**：資料，可以是 dict、list、numpy array 或另一個 DataFrame。
- **index**：每一列（row）的名稱，預設是 0, 1, 2...

In [2]:
import pandas as pd

strategy = pd.DataFrame({'annual_return': [0.2, 0.4, 0.5], 'risk': [0.3, 0.4, 0.5]}, index=['sma', 'rsi', 'kd'])
strategy

     annual_return  risk
sma            0.2   0.3
rsi            0.4   0.4
kd             0.5   0.5

## Series

取出 DataFrame 的一個欄位，就是一個 Series。

In [3]:
strategy['risk']

sma    0.3
rsi    0.4
kd     0.5
Name: risk, dtype: float64

## 運算

欄位之間可以直接運算，例如報酬 ÷ 風險（類似夏普率）：

In [4]:
strategy['annual_return'] / strategy['risk']

sma    0.666667
rsi    1.000000
kd     1.000000
dtype: float64

## 邏輯判斷

In [5]:
# 風險 <= 0.4 嗎？
strategy.risk <= 0.4

sma     True
rsi     True
kd     False
Name: risk, dtype: bool

## 篩選列

In [6]:
# 只留下風險 <= 0.4 的策略
strategy[strategy.risk <= 0.4]

     annual_return  risk
sma            0.2   0.3
rsi            0.4   0.4

## 改變資料形狀

[melt 文件](https://pandas.pydata.org/docs/reference/api/pandas.melt.html)

In [7]:
strategy.melt()

        variable  value
0  annual_return    0.2
1  annual_return    0.4
2  annual_return    0.5
3           risk    0.3
4           risk    0.4
5           risk    0.5